version: '3.8'
services:
  local:
    build: .
    command: bundle exec jekyll serve --watch --force_polling --host=0.0.0.0
    volumes:
      - .:/empire-penguin:rw
    ports:
      - "4000:4000"

  remote:
    build: .
    environment:
      - JEKYLL_ENV=production
    command: bundle exec jekyll build
    volumes:
      - .:/empire-penguin
    ports:
      - "4000:4000"

  cleanup:
    build: .
    command: rm -rf _site .sass-cache
    volumes:
      - .:/empire-penguin
    ports:
      - "4000:4000"

